# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

updates:
  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "master"

    commit-message:
      prefix: "github-actions (master)"

    # Disable rebasing for all pull requests
    rebase-strategy: "auto"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"

    open-pull-requests-limit: 10

    reviewers:
      - "mimmi20"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "8.1"

    commit-message:
      prefix: "github-actions (8.1)"

    # Disable rebasing for all pull requests
    rebase-strategy: "auto"
