# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

# file-version: 1.0

version: 2

updates:
  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    commit-message:
      prefix: "github-actions (master)"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "8.3"

    commit-message:
      prefix: "github-actions (8.3)"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"

  - package-ecosystem: "github-actions"

    directory: "/"

    schedule:
      interval: "daily"

    cooldown:
      default-days: 7

    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"

    assignees:
      - "mimmi20"

    labels:
      - "dependencies"

    target-branch: "8.4"

    commit-message:
      prefix: "github-actions (8.4)"

    ignore:
      - dependency-name: "mimmi20/ci"
      - dependency-name: "release-drafter/release-drafter"

    # Disable rebasing for all pull requests
    rebase-strategy: "disabled"
