name: "Lint GitHub Actions workflows"

on:
  pull_request:
    paths:
      - ".github/**"

jobs:
  actionlint:
    uses: "./.github/workflows/lint-actions.yml"
    with:
      skip-nasm-install: true
      skip-libimagequant-install: true

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  lint-status:
    name: "Lint Status"

    runs-on: "ubuntu-24.04"

    if: always()

    needs: "actionlint"

    steps:
      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1

      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) }}
        run: exit 0
