name: "Lint GitHub Actions workflows"

on:
  workflow_call:
    inputs:
      skip-nasm-install:
        required: true
        type: boolean
      skip-libimagequant-install:
        required: true
        type: boolean
      skip-libpng-install:
        required: true
        type: boolean
      skip-librabbitmq-install:
        required: true
        type: boolean
      skip-libgif-install:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  actionlint:
    name: "Install Node dependencies"

    runs-on: "${{ matrix.operating-system }}"
    timeout-minutes: 10

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

        node-version:
          - "24"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Set up NASM (for imagemin binary builds)"
        uses: "ilammy/setup-nasm@v1"
        if: inputs.skip-nasm-install == false

      - name: "install libimagequant-dev"
        run: "sudo apt-get install libimagequant-dev -y"
        if: inputs.skip-libimagequant-install == false

      - name: "install libpng-dev"
        run: "sudo apt-get install libpng-dev -y"
        if: inputs.skip-libpng-install == false

      - name: "install librabbitmq-dev"
        run: "sudo apt-get install librabbitmq-dev -y"
        if: inputs.skip-librabbitmq-install == false

      - name: "install libgif-dev"
        run: "sudo apt-get install libgif-dev"
        if: inputs.skip-libgif-install == false

      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: "actions/setup-node@v6"
        with:
          node-version: "${{ matrix.node-version }}"

      - name: "Check workflow files"
        id: "actionlint"
        uses: "raven-actions/actionlint@v2"
        with:
          matcher: true
          cache: true
          fail-on-error: false
          flags: "-ignore SC2086"
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Summary"
        if: ${{ steps.actionlint.outputs.exit-code != 0 }}  # example usage, do echo only when actionlint action failed
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
          exit 1

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  lint-status:
    name: "Lint Status"

    runs-on: "ubuntu-latest"

    if: always()

    needs: "actionlint"

    steps:
      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled')) }}
        run: exit 0
