name: "Lint GitHub Actions workflows"

on:
  pull_request:
    paths:
      - ".github/**"

jobs:
  actionlint:
    uses: "./lint-actions.yml"
    with:
      skip-nasm-install: true
      skip-libimagequant-install: true
