name: "Lint GitHub Actions workflows"

on:
  pull_request:
    paths:
      - ".github/**"

jobs:
  actionlint:
    uses: "mimmi20/ci/.github/workflows/lint-actions.yml@8.3"
    with:
      skip-nasm-install: true
      skip-libimagequant-install: true
