# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
  workflow_call:
    inputs:
      skip-validate-yaml:
        required: true
        type: boolean
      skip-validate-md:
        required: true
        type: boolean

permissions:
  contents: read

jobs:
  validate-yaml:
    name: "Validate yaml"

    runs-on: "${{ matrix.operating-system }}"
    timeout-minutes: 10
    continue-on-error: false

    if: inputs.skip-validate-yaml == false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Run yamllint"
        uses: "actionshub/yamllint@v1.8.3"

  markdownlint:
    name: "Validate markdown files"

    runs-on: "${{ matrix.operating-system }}"
    timeout-minutes: 10
    continue-on-error: false

    if: inputs.skip-validate-md == false

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Run markdownlint"
        uses: "DavidAnson/markdownlint-cli2-action@v23"
        with:
          globs: '*.md,**/*.md'
          separator: ','

  # This is a meta job to avoid to have to constantly change the protection rules
  # whenever we touch the matrix.
  lint-status:
    name: "Lint & Validate Status"

    runs-on: "ubuntu-latest"

    if: always()

    needs:
      - "validate-yaml"
      - "markdownlint"

    steps:
      - name: Failing run
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
        run: exit 1

      - name: Successful run
        if: ${{ !(contains(needs.*.result, 'failure')) && !(contains(needs.*.result, 'cancelled')) }}
        run: exit 0
